name = "PlutoRevise"
uuid = "d21d77ff-2495-4194-bdcf-4286a08d4d8f"
version = "0.1.0"
authors = ["Alberto Mengali <disberd@gmail.com>"]

[deps]
AbstractPlutoDingetjes = "6e696c72-6542-2067-7265-42206c756150"
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
AbstractPlutoDingetjes = "1.3.2"
CodeTracking = "3.0.0"
HypertextLiteral = "0.9.5"
Pkg = "1"
Revise = "3.13"
TOML = "1.0.3"
julia = "1.12"
